import { ProjectConfig } from "../types.ts";

const projectConfig: ProjectConfig[] = [
  {
    slug: "lightwell",
    header_color: "#39271D",
    body_color: "#39271D",
    font_color: "#F5F5F5",
    logo_color: "#F0EDE8",
    divider_color: "#F0EDE8",
    show_divider: false,
    project_title: "Lightwell Homes - Proxima Hub",
    body_title: null,
    font_family: "Cormorant Garamond",
    show_map: false,
    lat: 49.8850,
    lng: -119.4850,
    projects: [
      {
        name: "WILLA",
        disabled: false,
        featured: true,
        img_src: "/project_assets/lightwell/project/featured.jpg",
        overlay_img_src: "/project_assets/lightwell/project/card_logo.png",
        url: "https://willa.proximahq.io",
        text_color: "white",
        lng: -123.068772,
			  lat: 49.308507,
        projectId: "c816a037-f4b5-456f-ab7f-e123e5d774e2"
      },
      {
        name: "Ansoku",
        disabled: false,
        featured: true,
        img_src: "/project_assets/lightwell/project/Granville_front view.jpg",
        overlay_img_src: "/project_assets/lightwell/project/logo2.png",
        url: "https://ansoku.proximahq.io/",
        text_color: "white",
        lng: -123.064662,
        lat: 49.308507,
        projectId: "ccdf5d34-9946-499b-9f35-7f9da1560f05"
      },
      {
        name: "Solin",
        disabled: false,
        featured: false,
        img_src: "/project_assets/lightwell/project/930_front view_01.08.jpg",
        overlay_img_src: "/project_assets/lightwell/project/Logo-White.svg",
        url: "https://solin.proximahq.io/",
        text_color: "white",
        lng: -123.066877,
        lat: 49.308507,
        projectId: "6e456265-38c1-4efe-95ec-dec4b5299149"
      },
    ],
  },
  {
    slug: "neighbour",
    header_color: "#F5F783",
    body_color: "#F5F783",
    font_color: "#1e1e1e",
    logo_color: "#F0EDE8",
    divider_color: "#F0EDE8",
    show_divider: false,
    project_title: "Neighbour - Proxima Hub",
    body_title: null,
    font_family: "MnkyJaneCondensed",
    is_wide_logo: true,
    show_map: false,
    projects: [
      {
        name: "Traditional",
        disabled: false,
        featured: true,
        img_src: '',
        overlay_img_src: null,
        url: "https://neighbour.proximahq.io/",
        text_color: "black",
        background_color: "#CCD3D9",
        no_image: true,
        lat: 49.8851,
        lng: -119.4856,
      },
      {
        name: "Co-Live",
        disabled: false,
        featured: false,
        img_src: '',
        overlay_img_src: null,
        url: 'https://neighbourcolive.proximahq.io/',
        text_color: "white",
        background_color: "#4078BE",
        no_image: true,
        lat: 49.8851,
        lng: -119.4856,
      },
    ],
  },
];

export default projectConfig;
